fix: remove external:debug from esbuild bundle
```
Run redhat-plumbers-in-action/tracker-validator@v3
node:internal/modules/cjs/loader:1476
  const err = new Error(message);
              ^
Error: Cannot find module 'debug'
Require stack:
- /home/runner/work/_actions/redhat-plumbers-in-action/tracker-validator/v3/dist/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1476:15)
    at wrapResolveFilename (node:internal/modules/cjs/loader:1049:27)
    at defaultResolveImplForCJSLoading (node:internal/modules/cjs/loader:1073:10)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1094:12)
    at Module._load (node:internal/modules/cjs/loader:1262:25)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1576:12)
    at require (node:internal/modules/helpers:153:16)
    at node_modules/https-proxy-agent/dist/agent.js (file:///home/runner/work/_actions/redhat-plumbers-in-action/tracker-validator/v3/dist/main.js:47048:35)
    at __require2 (file:///home/runner/work/_actions/redhat-plumbers-in-action/tracker-validator/v3/dist/main.js:18:50) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/redhat-plumbers-in-action/tracker-validator/v3/dist/main.js'
  ]
}
Node.js v24.15.0
```